name: macOS Build

#on:
#  repository_dispatch:
#    types: [bitbucket_push]
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest 

    steps:
    

    - name: Build project
      run: |
        mkdir -p dist
        echo "test1k54664343sdjf" > dist/1.py
        ls dist/

    - name: Upload to Existing Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: README.md
        repository: irellik/test--release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 GitHub Token
